"use client";

import { useEffect, useRef, useState } from "react";
import type { HttpView, InspectorEvent, TokenView } from "@/lib/inspector";

const CLAIM_NOTES: Record<string, string> = {
  sub: "Subject – the user this token represents",
  act: "Actor – the AI agent acting on the user's behalf",
  aud: "Audience – the only API that accepts this token",
  scp: "Scopes – exactly what this token may do",
  scope: "Scopes – exactly what this token may do",
  exp: "Expiry – short-lived by design",
  iat: "Issued at",
  iss: "Issuer – your Okta authorization server",
  cid: "Client – the app that requested the token",
  uid: "Okta user id",
  amr: "How the user proved it was them",
  binding_message: "What the user saw and approved",
  name: "User's display name",
  email: "User's email",
  nonce: "Replay protection for sign-in",
  jti: "Unique token id",
};

const KEY_CLAIMS = new Set(["sub", "act", "aud", "scp", "scope", "exp", "binding_message"]);

function formatClaim(key: string, value: unknown) {
  if ((key === "exp" || key === "iat") && typeof value === "number") {
    const delta = value - Math.floor(Date.now() / 1000);
    const when = new Date(value * 1000).toLocaleTimeString();
    if (key === "iat") return when;
    return delta > 0 ? `${when} (in ${delta >= 120 ? `${Math.round(delta / 60)} min` : `${delta}s`})` : `${when} (expired)`;
  }
  return typeof value === "string" ? value : JSON.stringify(value);
}

function ColoredJwt({ raw }: { raw: string }) {
  const parts = raw.split(".");
  if (parts.length !== 3) return <div className="raw-jwt">{raw}</div>;
  return (
    <div className="raw-jwt">
      <span className="jwt-h">{parts[0]}</span>.<span className="jwt-p">{parts[1]}</span>.<span className="jwt-s">{parts[2]}</span>
    </div>
  );
}

function TokenCard({ token }: { token: TokenView }) {
  const [showRaw, setShowRaw] = useState(false);
  if (!token.payload) {
    return (
      <>
        <div className="section-label">{token.label} · opaque secret</div>
        <pre className="code">{token.raw}</pre>
      </>
    );
  }
  const entries = Object.entries(token.payload).sort(([a], [b]) => Number(KEY_CLAIMS.has(b)) - Number(KEY_CLAIMS.has(a)));
  return (
    <>
      <div className="section-label">{token.label} · decoded JWT</div>
      <table className="claims">
        <tbody>
          {entries.map(([k, v]) => (
            <tr key={k} className={KEY_CLAIMS.has(k) ? "key" : undefined}>
              <td className="k">{k}</td>
              <td className="v">{formatClaim(k, v)}</td>
              <td className="why">{CLAIM_NOTES[k] ?? ""}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <button className="btn" style={{ marginTop: 6, fontSize: 12 }} onClick={() => setShowRaw((s) => !s)}>
        {showRaw ? "Hide" : "Show"} raw token & header
      </button>
      {showRaw && (
        <>
          <pre className="code">{JSON.stringify(token.header, null, 2)}</pre>
          <ColoredJwt raw={token.raw} />
        </>
      )}
    </>
  );
}

function HttpCard({ http, expanded }: { http: HttpView; expanded: boolean }) {
  const ok = http.status !== undefined && http.status < 400;
  return (
    <>
      <div className="http-line">
        {http.method} {http.url}
        {http.status !== undefined && (
          <>
            {" → "}
            <span className={`status ${ok ? "status-ok" : "status-bad"}`}>{http.status}</span>
          </>
        )}
        {http.simulated && <span className="sim" title="Generated by the offline mock IdP">simulated</span>}
      </div>
      {expanded && (
        <>
          {http.requestHeaders && (
            <>
              <div className="section-label">Headers</div>
              <pre className="code">{Object.entries(http.requestHeaders).map(([k, v]) => `${k}: ${v}`).join("\n")}</pre>
            </>
          )}
          {http.requestBody !== undefined && (
            <>
              <div className="section-label">Request</div>
              <pre className="code">{JSON.stringify(http.requestBody, null, 2)}</pre>
            </>
          )}
          {http.responseBody !== undefined && (
            <>
              <div className="section-label">Response</div>
              <pre className="code">{JSON.stringify(http.responseBody, null, 2)}</pre>
            </>
          )}
        </>
      )}
    </>
  );
}

function EventCard({ event, showHttp, resolved }: { event: InspectorEvent; showHttp: boolean; resolved?: string }) {
  const [open, setOpen] = useState(event.kind === "token" || event.kind === "warning");
  const expandable = Boolean(event.token || event.http);
  return (
    <div className={`event kind-${event.kind}`}>
      <div className="event-head" onClick={() => expandable && setOpen((o) => !o)}>
        <span className="event-title">
          {expandable && <span className="muted">{open ? "▾ " : "▸ "}</span>}
          {event.title}
        </span>
        <span className="event-time">{new Date(event.ts).toLocaleTimeString()}</span>
      </div>
      {event.detail && <div className="event-detail">{event.detail}</div>}
      {event.tags && event.tags.length > 0 && (
        <div className="tags">
          {event.tags.map((t) => (
            <span key={t} className="tag">
              {t}
            </span>
          ))}
        </div>
      )}
      {event.approval && (
        <div className="approval-box">
          {resolved ? <strong>{resolved}</strong> : <span className="pulse" />}
          <span style={{ flex: 1 }}>“{event.approval.bindingMessage}”</span>
          {!resolved && event.approval.approveUrl && (
            <a className="btn" href={event.approval.approveUrl} target="_blank" rel="noreferrer">
              Open approver
            </a>
          )}
        </div>
      )}
      {event.http && <HttpCard http={event.http} expanded={open && showHttp} />}
      {open && event.token && <TokenCard token={event.token} />}
    </div>
  );
}

/** An approval is settled once a later CIBA event reports a token or a failure. */
function approvalOutcome(events: InspectorEvent[], index: number) {
  const next = events.slice(index + 1).find((e) => e.tags?.includes("ciba") && (e.kind === "token" || e.kind === "error"));
  if (!next) return undefined;
  return next.kind === "token" ? "Approved ✓" : "Not approved ✕";
}

export function Inspector({ events, onClear }: { events: InspectorEvent[]; onClear: () => void }) {
  const [showHttp, setShowHttp] = useState(true);
  const end = useRef<HTMLDivElement>(null);
  useEffect(() => end.current?.scrollIntoView({ behavior: "smooth" }), [events.length]);

  return (
    <section className="inspector">
      <div className="pane-head">
        Token inspector <span className="muted">· what Okta is doing for the agent</span>
        <span className="spacer" />
        <label className="toggle" style={{ fontWeight: 400, fontSize: 13 }}>
          <input type="checkbox" checked={showHttp} onChange={(e) => setShowHttp(e.target.checked)} /> HTTP details
        </label>
        <button className="btn" style={{ fontSize: 12 }} onClick={onClear}>
          Clear
        </button>
      </div>
      <div className="events">
        {events.length === 0 && <div className="empty">Identity events will appear here as the agent works.</div>}
        {events.map((e, i) => (
          <EventCard key={e.id} event={e} showHttp={showHttp} resolved={e.approval ? approvalOutcome(events, i) : undefined} />
        ))}
        <div ref={end} />
      </div>
    </section>
  );
}
